# Generated by Django 3.1.1 on 2020-09-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerProcessState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(max_length=255, unique=True)),
                ('info', models.JSONField(default=dict)),
                ('info_version', models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProcessState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='process_state', serialize=False, to='roost_backend.user')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zclass', models.CharField(max_length=255)),
                ('zinstance', models.CharField(max_length=255)),
                ('zrecipient', models.CharField(max_length=255)),
                ('class_key', models.CharField(max_length=255)),
                ('instance_key', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roost_backend.user')),
            ],
            options={
                'unique_together': {('user', 'zrecipient', 'class_key', 'instance_key')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zclass', models.CharField(max_length=255)),
                ('zinstance', models.CharField(max_length=255)),
                ('class_key', models.CharField(max_length=255)),
                ('instance_key', models.CharField(max_length=255)),
                ('class_key_base', models.CharField(max_length=255)),
                ('instance_key_base', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('receive_time', models.DateTimeField(auto_now_add=True)),
                ('auth', models.BooleanField()),
                ('sender', models.CharField(db_index=True, max_length=255)),
                ('recipient', models.CharField(blank=True, db_index=True, max_length=255)),
                ('conversation', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_personal', models.BooleanField(db_index=True)),
                ('is_outgoing', models.BooleanField()),
                ('uid', models.CharField(max_length=16)),
                ('opcode', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('users', models.ManyToManyField(to='roost_backend.User')),
            ],
            options={
                'ordering': ['id'],
                'index_together': {('class_key', 'instance_key'), ('class_key_base', 'instance_key_base')},
            },
        ),
    ]
