# Generated by Django 4.2.30 on 2026-05-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roost_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='roost_backe_class_k_d8a963_idx',
            old_fields=('class_key', 'instance_key'),
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='roost_backe_class_k_059cc7_idx',
            old_fields=('class_key_base', 'instance_key_base'),
        ),
    ]
